export const CHANGE_FROM_CURRENCY = "CHANGE_FROM_CURRENCY";
export const CHANGE_TO_CURRENCY = "CHANGE_TO_CURRENCY";
export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const CHANGE_TRANSACTION_ID = "CHANGE_TRANSACTION_ID";